import React from 'react';
import { Helmet } from 'react-helmet-async';

export default function TermsOfService() {
  return (
    <>
      <Helmet>
        <title>Terms of Service | Clean Estimator</title>
        <link rel="canonical" href="https://www.cleanestimator.com/terms-of-service" />
      </Helmet>
      <div style={{ background: '#f8fafc', minHeight: '100vh' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', padding: 'clamp(28px, 7vw, 56px) 20px 10px' }}>
          <h1 style={{ fontSize: 'clamp(26px, 6vw, 36px)', fontWeight: 900, color: '#0f172a', marginBottom: 8, letterSpacing: '-0.01em' }}>Terms of Service</h1>
          <p style={{ color: '#64748b' }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>
        <div style={{ maxWidth: 760, margin: '0 auto', padding: '20px 20px clamp(40px, 8vw, 64px)', lineHeight: 1.65, display: 'flex', flexDirection: 'column', gap: 14 }}>
          {[
            ['Acceptance', 'By using Clean Estimator, you agree to these terms. If you don\'t agree, please don\'t use the service.'],
            ['Description of Service', 'Clean Estimator provides an online tool for estimating cleaning service costs. For cleaning companies, we provide an embeddable widget and lead management dashboard ("Company Services").'],
            ['Estimates Are Not Quotes', 'All price estimates generated by Clean Estimator are for informational purposes only and do not constitute quotes, contracts, or guarantees. Actual cleaning service costs may vary significantly. Clean Estimator is not responsible for any financial decisions made based on these estimates.'],
            ['Company Accounts', 'Company accounts are for cleaning service businesses. You must provide accurate information when registering. You are responsible for keeping your account credentials secure. You may not share your account with other businesses.'],
            ['Subscription and Payment', 'Company Services are available on a paid subscription basis ($159/month) after a 30-day free trial. No credit card is required to start the trial. Payments are processed by Stripe. Subscriptions auto-renew monthly. You may cancel at any time through the billing portal; cancellation takes effect at the end of the current billing period.'],
            ['Refunds', 'We do not offer refunds for partial months. If you cancel before your trial ends, you will not be charged.'],
            ['Prohibited Uses', 'You may not use Clean Estimator to: (a) generate false or misleading pricing information; (b) scrape or harvest data at scale; (c) attempt to access other users\' accounts; (d) use the service for any illegal purpose.'],
            ['Disclaimer of Warranties', 'Clean Estimator is provided "as is" without warranties of any kind. We do not warrant that estimates are accurate, complete, or suitable for any particular purpose.'],
            ['Limitation of Liability', 'Clean Estimator\'s total liability to you for any claims arising from use of the service is limited to the amount you paid us in the 3 months prior to the claim, or $50, whichever is greater.'],
            ['Termination', 'We may suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting support.'],
            ['Governing Law', 'These terms are governed by the laws of the State of Delaware, USA.'],
            ['Contact', 'Questions about these terms? Email info@cleanestimator.com.'],
          ].map(([title, body], i) => (
            <div key={title} style={{ background: 'white', border: '1px solid #e2e8f0', borderRadius: 14, padding: '18px 20px', display: 'flex', gap: 14 }}>
              <span style={{ width: 26, height: 26, borderRadius: 8, background: '#eff6ff', color: '#1d4ed8', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: 12.5, fontWeight: 800 }}>{i + 1}</span>
              <div>
                <h2 style={{ fontSize: 16, fontWeight: 700, color: '#0f172a', marginBottom: 6 }}>{title}</h2>
                <p style={{ color: '#475569', fontSize: 14.5, margin: 0 }}>{body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
